### ISSUE TITLE
Stopped working for some reason after last ST3 update

### ISSUE THREAD

**Issue by taasaa** [irohiroki/RubyBlockConverter#10]
ST3 version: build 3064

The trace i see in the ST console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "RubyBlockConverter in /Users/michael/Library/Application Support/Sublime Text 3/Installed Packages/Ruby Block Converter.sublime-package", line 133, in run
  File "RubyBlockConverter in /Users/michael/Library/Application Support/Sublime Text 3/Installed Packages/Ruby Block Converter.sublime-package", line 42, in match_blocks
  File "./tokenize.py", line 550, in _tokenize
tokenize.TokenError: ('EOF in multi-line statement', (940, 0))
```

Any ideas? 
Thanks!

**Comment by irohiroki** [comment]
taasaa,
Probably your code has an syntax error. since the plugin uses sublime's built-in tokenizer, code must be syntactically correct so that the tokenizer could parse it.
This is a limitation of the plugin. too bad.

**Comment by taasaa** [comment]
Hiroki,

I don't think that's the problem in this case, my code is working and ruby
linter is happy with it. But i understand that there's not much you can do
here if you depend on built in tokenizer to do the work.

Thanks anyway, i'll continue to look for the problem.

**Comment by irohiroki** [comment]
hope the tokenizer will be developed in the later release of sublime.
