### ISSUE TITLE
tokenize TokenError 'EOF in multi-line statement'

### ISSUE THREAD

**Issue by dsandstrom** [irohiroki/RubyBlockConverter#5]
Is this package compatible with RSpec?

Using, my latest commit, I get:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./RubyBlockConverter.py", line 75, in run
    self.blocks = match_blocks(self, tokenize.OP, '{', '}')
  File "./RubyBlockConverter.py", line 42, in match_blocks
    for num, val, start, _, _ in tokens:
  File ".\tokenize.py", line 352, in generate_tokens
tokenize.TokenError: ('EOF in multi-line statement', (763, 0))

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./RubyBlockConverter.py", line 126, in run
    self.blocks = match_blocks(self, tokenize.NAME, 'do', 'end')
  File "./RubyBlockConverter.py", line 42, in match_blocks
    for num, val, start, _, _ in tokens:
  File ".\tokenize.py", line 352, in generate_tokens
tokenize.TokenError: ('EOF in multi-line statement', (763, 0))
```

**Comment by dsandstrom** [comment]
It is working on a different RSpec file.   Maybe there is something wrong with the EOF or EOL of the file I was trying it on. 

I ran `dos2unix` on the file, but no change.

By the way, thanks for this plugin, something I've been looking for in a while, wish I found it earlier.

**Comment by alphaone** [comment]
I can't reproduce this. Is this happening in each of your spec-files? Are you willing to provide an example?

**Comment by dsandstrom** [comment]
It is not happening to all spec files.  I'll upload an example.

**Comment by dsandstrom** [comment]
I get a similar error when there is an indentation mismatch, for example:

```
    foo { bar }

    foo do
      bar
    end
  asdf
sadf
```

gives: 

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./RubyBlockConverter.py", line 126, in run
  File "./RubyBlockConverter.py", line 42, in match_blocks
  File ".\tokenize.py", line 346, in generate_tokens
  File "<tokenize>", line 6
    asdf
    ^
IndentationError: unindent does not match any outer indentation level
```

However, this is not the problem I was having previously (and probably not a priority bug).  A thing to note, with both cases, is I receive the errors anytime I press the key binding, not just if the cursor is in brackets or do-end.  With the other errors I reported, the error `('EOF in multi-line statement', (763, 0))`, is pointing to the line after my last line of code.

**Comment by dsandstrom** [comment]
I think I found what is causing the previous error, a pound sign (#), in an array of strings shortcut, `%w(array of strings)`.  I don't know the official title.  Here is the reproducible code:

```
%w(#).each do
  foo { bar }

  foo do
    bar
  end
end
```

gives:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./RubyBlockConverter.py", line 126, in run
  File "./RubyBlockConverter.py", line 42, in match_blocks
  File ".\tokenize.py", line 352, in generate_tokens
tokenize.TokenError: ('EOF in multi-line statement', (8, 0))
```

`['#'].each do` works fine.

**Comment by irohiroki** [comment]
too bad, it seems caused because of the poor builtin tokenizer, that takes `#` the beginning of a comment, I guess. I'm sorry but I don't think I have any means to address this issue.

**Comment by dsandstrom** [comment]
Alright, thanks for taking a look.
